name: sahakosh
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  google_fonts: ^3.0.1
  image_picker: ^0.8.6
  cached_network_image: ^3.2.3
  syncfusion_flutter_calendar: ^20.4.43
  percent_indicator: ^4.2.2
  url_launcher: ^6.1.7


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - lib/startup_ui/domain/dummy.json
    - lib/notification_ui/startup/domain/startup_domain_dummy.json
    - lib/notification_ui/investor/domain/investor_domain_dummy.json
    - assets/logo.png
    - assets/ibutton.png
