name: sahakosh
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  flutter:
    sdk: flutter
  image_picker: ^0.8.6

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: latobold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: latolight
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
    - family: robotobold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: robotolight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf

  assets:
    - assets/images/
