name: sahakosh
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  flutter:
    sdk: flutter
  image_picker: ^0.8.6

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: latobold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: latolight
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
    - family: robotobold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: robotolight
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf

  assets:
    - assets/images/
    - lib/startup_ui/domain/dummy.json
    - assets/logo.png
    - assets/ibutton.png
  
