// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkylnkSipWzrtQK-DLLJj__fBoBLPeesM',
    appId: '1:362956023018:web:3ac58bdc29e3698969a393',
    messagingSenderId: '362956023018',
    projectId: 'sahakosh-ce8b0',
    authDomain: 'sahakosh-ce8b0.firebaseapp.com',
    storageBucket: 'sahakosh-ce8b0.appspot.com',
    measurementId: 'G-T9L0WKMRBQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5l0H_q0u0Jor52_q58reI2Or-4rhHSN8',
    appId: '1:362956023018:android:e3b71a3e86892ef869a393',
    messagingSenderId: '362956023018',
    projectId: 'sahakosh-ce8b0',
    storageBucket: 'sahakosh-ce8b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvmduKuKWuTursOrjyW32adGErL8J-A2I',
    appId: '1:362956023018:ios:6677890454a4bfbe69a393',
    messagingSenderId: '362956023018',
    projectId: 'sahakosh-ce8b0',
    storageBucket: 'sahakosh-ce8b0.appspot.com',
    iosClientId: '362956023018-1729q23u4vtl29mhlj4seg81rlenevfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahakosh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvmduKuKWuTursOrjyW32adGErL8J-A2I',
    appId: '1:362956023018:ios:6677890454a4bfbe69a393',
    messagingSenderId: '362956023018',
    projectId: 'sahakosh-ce8b0',
    storageBucket: 'sahakosh-ce8b0.appspot.com',
    iosClientId: '362956023018-1729q23u4vtl29mhlj4seg81rlenevfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.sahakosh',
  );
}
