import 'package:sahakosh/investor_ui/domain/investor_model.dart';

var InvestorDummy = [
  InvestorModel(
      name: "Google",
      owner: "Aayush Gelal",
      image: "https://cdn.zeebiz.com/sites/default/files/styles/zeebiz_850x478/public/2022/02/19/175856-google-22reuters.jpg?itok=lXyy1RwM",
      address: "Lazimpat Kathmandu",
      amountWithdrawn: true,
      category: "Tech",
      createdOn: "yesterday",
      equity: "5%",
      long_description: "Using AI and automation to improve the production of chemicals and materials.",
      operating_yrs: "4 years",
      target: 130500,
      valuation: 4000000,
      raisingAmount: 100000,
      targetReached: false),
  InvestorModel(
    name: "Inve_stup",
    owner: "Subarna",
    image: "https://images.wsj.net/im-584189?width=860&height=573",
    address: "Lazimpat Kathmandu",
    amountWithdrawn: true,
    category: "Tech",
    createdOn: "yesterday",
    equity: "5%",
    long_description: "Utilizing natural language processing and machine learning to provide financial data analytics",
    operating_yrs: "2 years",
    target: 230000,
    targetReached: false,
    valuation: 4000000,
    raisingAmount: 100000,
  ),
  InvestorModel(
    name: "Pay Request",
    owner: "Shree Krishna",
    image: "https://media.payrequest.nl/wp-content/uploads/2021/09/18012141/blog-image.png",
    address: "Lazimpat Kathmandu",
    amountWithdrawn: true,
    category: "Tech",
    createdOn: "yesterday",
    equity: "5%",
    long_description: "This is a long description of how it looks where there are many things",
    operating_yrs: "3 years",
    target: 3000000,
    targetReached: false,
    raisingAmount: 100000,
    valuation: 40000000,
  ),
  InvestorModel(
    name: "Influx Image",
    owner: "Rabin Acharya",
    image:
        "https://static.wixstatic.com/media/cd139e_1aa9b9bb44ed4d0b82fe92d47b5dc8c6~mv2.jpg/v1/fill/w_1178,h_738,al_c/cd139e_1aa9b9bb44ed4d0b82fe92d47b5dc8c6~mv2.jpg",
    address: "Lazimpat Kathmandu",
    amountWithdrawn: true,
    category: "Tech",
    createdOn: "yesterday",
    equity: "5%",
    long_description: "This is a long description of how it looks where there are many things",
    operating_yrs: "3 years",
    target: 130000,
    targetReached: false,
    valuation: 400000000,
    raisingAmount: 100000,
  ),
  InvestorModel(
    name: "Startup Tips",
    owner: "Aayush Gelal",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwLxOZ4hErPxltsnLyVjmgVdP7O5wqFtRwiaphZgzhH6qnbzjZzv5Ebo-TJhMozmKOYAo&usqp=CAU",
    address: "Lazimpat Kathmandu",
    amountWithdrawn: true,
    category: "Tech",
    createdOn: "yesterday",
    equity: "5%",
    long_description: "This is a long description of how it looks where there are many things",
    operating_yrs: "3 years",
    target: 1230000,
    targetReached: false,
    valuation: 40000000,
    raisingAmount: 100000,
  )
];
